api-url: "http://127.0.0.1:8000"
update-interval-seconds: 60
default-role: "default"
# update-times:
#   - "00:00"
#   - "05:00"
#   - "18:00"

# Роль для операторов (OP)
op-role-enabled: true
op-role-name: "op"

# Команды, для которых обязательно указывать время (в любом аргументе)
time-required-commands:
  - "/ban"
  - "/mute"
  - "/jail"
  - "/tempban"
  - "/tempmute"
